client:
  port: 8080
  debug: false
  path: "/app/client/dist"
  ## this will require during authentication. Use random secret.
  # openssl rand -hex 32
  # OR
  # cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 36 | head -n 1
  api_key: PLUG_N_MEET_API_KEY
  secret: PLUG_N_MEET_SECRET
  webhook_conf:
    # enable webhook. This will post response for different events
    enable: false
    # set url bellow. This will be use as global.
    # this is optional
    url: ""
    # During create room you can set custom hook URL too.
    # if you set enable_for_per_meeting: true
    # then extra post response will send in that address too
    enable_for_per_meeting: false
log_settings:
  log_file: "/app/log/plugNmeet.log"
  # maxsize of log file in MB
  maxsize: 20
  maxbackups: 4
  # max age of log before rotate in days
  maxage: 2
livekit_info:
  host: "http://localhost:7880"
  api_key: LIVEKIT_API_KEY
  secret: LIVEKIT_SECRET
  # value in minutes. Default 10 minutes. Client will renew token automatically
  token_validity: 10m
redis_info:
  host: localhost
  port: "6379"
  username: ""
  password: ""
  db: 0
mysql_info:
  host: localhost
  port: "3306"
  username: "root"
  password: "DB_ROOT_PASSWORD"
  db: "plugnmeet"
  prefix: "pnm_"
upload_file_settings:
  path: "/app/upload"
  # file size in MB. Default 10MB
  max_size: 10
  # By default, files will be deleted as soon as the session will be finish.
  # You can set it true to disable deleting files.
  keep_forever: false
  allowed_types:
    - "jpg"
    - "png"
    - "pdf"
    - "docx"
    - "txt"
recorder_info:
  # this value should be same as recorder's copy_to_dir path
  recording_files_path: "/app/recording_files"
  token_validity: 30m