version: "3"
services:
  redis:
    image: redis
    restart: on-failure
    network_mode: "host"
  db:
    image: mariadb:10.6
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASSWORD
    network_mode: "host"
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./sql_dump/install.sql:/docker-entrypoint-initdb.d/install.sql
  livekit:
    image: livekit/livekit-server
    restart: on-failure
    network_mode: "host"
    volumes:
      - .:/app
    command: --config "/app/livekit.yaml"
    depends_on:
      - redis
  plugnmeet-api:
    image: mynaparrot/plugnmeet-server
    restart: on-failure
    network_mode: "host"
    volumes:
      - .:/app
    command: --config "/app/config.yaml"
    depends_on:
      - db
      - redis
      - livekit
