version: "3"
services:
  redis:
    image: redis:6
    restart: always
    network_mode: "host"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 1s
      retries: 5
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: DB_ROOT_PASSWORD
    network_mode: "host"
    healthcheck:
      test: "mysql -u root --password=$$MYSQL_ROOT_PASSWORD --execute \"SHOW DATABASES;\""
      interval: 10s
      timeout: 1s
      retries: 5
    volumes:
      - ./mariadb-data:/var/lib/mysql
      - ./sql_dump/install.sql:/docker-entrypoint-initdb.d/install.sql
  livekit:
    image: livekit/livekit-server
    restart: always
    network_mode: "host"
    volumes:
      - .:/app
    command: --config "/app/livekit.yaml"
    depends_on:
      - redis
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:7880 || exit 1
      interval: 20s
      timeout: 1s
      retries: 5
  etherpad:
    image: mynaparrot/plugnmeet-etherpad
    restart: always
    network_mode: "host"
    volumes:
      - ./etherpad/APIKEY.txt:/opt/etherpad-lite/APIKEY.txt
      - ./etherpad/settings.json:/opt/etherpad-lite/settings.json
      - /usr/share/fonts/:/usr/share/fonts/:ro
      - /etc/fonts/:/etc/fonts/:ro
      - /usr/share/fontconfig/:/usr/share/fontconfig/:ro
      - /var/cache/fontconfig/:/var/cache/fontconfig/:ro
    depends_on:
      - redis
  plugnmeet:
    image: mynaparrot/plugnmeet-server
    restart: always
    network_mode: "host"
    volumes:
      - .:/app
      - /usr/share/fonts/:/usr/share/fonts/:ro
      - /etc/fonts/:/etc/fonts/:ro
      - /usr/share/fontconfig/:/usr/share/fontconfig/:ro
      - /var/cache/fontconfig/:/var/cache/fontconfig/:ro
    command: --config "/app/config.yaml"
    depends_on:
      - db
      - redis
      - livekit
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8080 || exit 1
      interval: 20s
      timeout: 1s
      retries: 5
